### ISSUE TITLE
Definitions section is missing from TOC

### ISSUE THREAD

**Issue by Bez625** [nrinaudo/scala-best-practices#44]
I found a section on of your website on TypeClasses through google featured snippets. Digging around a bit it seems this section is missing from the TOC so I pulled the repo and had a little play with it. I think it looks like you intended to add it at the bottom of the TOC in `src/site/config.yml` :
```
  definitions:
    output:   true
```
Changing to this seems to be the simple fix (if I read your intention correctly)
```
  definitions:
    output:   true
    title:    Definitions
    sequence: 9
```

I was going to PR in, but it looks like that's locked down (like the rest of the world right now!)

BTW I caught your talk on Scala Best Practices at Scala Days 2019 and really appreciate this guide/reference doc :-).

**Comment by nrinaudo** [comment]
Weird as this might seem, it's actually intended: the TOC only lists best practices, definitions are linked from them.

The definitions I give here tend to be correct, but not necessarily complete - they're not the focus, and I prefer it that way.

That being said, it looks like the type class definition is not actually linked from anywhere, and I'll need to fix it - I was certain the structural types page linked there, but apparently I was wrong. Thanks!

Not sure about the PRs being locked, I don't think that was intentional. Let me see if I can re-open them.

I'm glad that this, and the accompanying talk, are useful to you - that's exactly what I went through the trouble, and positive feedback like yours make it worthwhile. Thanks!

**Comment by nrinaudo** [comment]
Ah, yes, the type class definition *is* linked from the structural types article - in the general rule, and once more towards the middle. I'm not 100% mad yet.

**Comment by Bez625** [comment]
Fair enough! I have a way to add the definitions in locally if i want to go over them so i've learned a little a least. 

FWIW I got the below trying to push the branch, I didn't try particularly hard though so it could be something to do with my github settings:
```git push -u origin add_definitions_to_toc 
ERROR: Permission to nrinaudo/scala-best-practices.git denied to Bez625.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

Thanks again!

**Comment by nrinaudo** [comment]
Oh right. It’s not the PRs that are closed, it’s just write access to my repo. You need to fork the repo, do your changes in a branch, and github will allow you to PR from your fork to my repo. That’s the standard way of doing things on GitHub, I believe?
